# Generated by Django 2.2.7 on 2019-11-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='incorrect_answer1',
            new_name='incorrect_answer_1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='incorrect_answer2',
            new_name='incorrect_answer_2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='incorrect_answer3',
            new_name='incorrect_answer_3',
        ),
    ]
