# Generated by Django 2.2.7 on 2019-11-22 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20191121_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='incorrect_answer_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='incorrect_answer_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='incorrect_answer_3',
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=63)),
                ('correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question')),
            ],
            options={
                'unique_together': {('question', 'choice_text')},
            },
        ),
    ]
